chime: force non-ab update package
AssertionError: META/ab_partitions.txt is required for ab_update.

Signed-off-by: Joe7500 <j7545032@gmail.com>

Former-commit-id: e6a0b70c3547f9bd667eade578ebd5e56a932a25