chime: force non-ab update package
AssertionError: META/ab_partitions.txt is required for ab_update.

Signed-off-by: Joe7500 <j7545032@gmail.com>

Former-commit-id: 1dff941af26ecfbc9e2eef92861209b87bebcd8f